[project]
name = "python-stepik-tester"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "rich",
    "requests",
    "pyclip>=0.7.0",
    "loguru>=0.7.3",
]
